#!/usr/bin/env python3
"""Generate fixed-point lookup tables (the game never uses the FPU)."""
import math
import sys

out = open(sys.argv[1], "w")
out.write("/* Generated by tools/gentables.py */\n")
out.write("const short g_sinTab[1024]={\n")
vals = [int(round(math.sin(i * 2 * math.pi / 1024) * 16384)) for i in range(1024)]
for i in range(0, 1024, 16):
    out.write(",".join(str(v) for v in vals[i:i + 16]) + ",\n")
out.write("};\n")
# atan table: atan(i/256) for i in 0..256 in 1024-units per circle
out.write("const unsigned short g_atanTab[257]={\n")
vals = [int(round(math.atan(i / 256.0) * 1024 / (2 * math.pi))) for i in range(257)]
out.write(",".join(str(v) for v in vals) + "\n};\n")
